services:
  db:
    image: mysql:8.0
    container_name: room_db
    restart: always
    environment:
      MYSQL_DATABASE: room_management_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: room_backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:@db:3306/room_management_db
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GEMINI_API_KEY=your_key
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: room_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: